### ISSUE TITLE
relative paths

### ISSUE THREAD

**Issue by noerw** [petko10/rhythmbox-plugin-playlists-import-export#11]
would be nice if the generated m3u files contained relative paths to the export directory

**Comment by petko10** [comment]
It would, but I'm using the Rhythmbox playlist manager class, and it does not support exporting with relative paths. I'll be happy if someone contributed the feature, but it's not a priority for me as of now, sorry.

**Comment by lachlan-00** [comment]
Is there a reason for relative paths over the full path? I've just started playing around with this plugin to sync my ampache playlists and i don't understand the benefit of shorter paths

**Comment by noerw** [comment]
The reason is, absolute paths are not portable. The playlist will break if you move any of the files or the playlist itself, or if you copy it to another device.
As this is an 'exporter' I consider portability a big feature

**Comment by lachlan-00** [comment]
Ah, that makes sence. This could be an option for exports.

I've just started playing around with the plugin so I'll look at that too.

**Comment by lachlan-00** [comment]
I've been working on other things but I think I know what I would do with this one.

An export to the RB library base path keeping the source/export files intact.

Once that's done I can add options to put playlists with the highest folder in the path.

EG, /home/user/Music/5star.m3u by default.

Then for a playlist for with just an album/artist put the m3u into the subfolder.
/home/user/Music/Mortiis/mortiis.m3u
/home/user/Music/Tool/Undertow/undertow.m3u

Would something like that suit?

(The m3u would obviously remove the path from it's current dir on creation.)

**Comment by noerw** [comment]
didn't think about automatic selection of the appropriate playlist storage location, sounds perfec! but maybe give the option to override this location with a custom path?

**Comment by petko10** [comment]
Could you explain the idea a bit more? As far as I could understand you want to check the playlist items and for playlists that contain only items in a certain folder - export them to that folder. But that would not make the playlists contain relative paths (to that folder) if you still export them using the Rhythmbox PlaylistsManager , unless I'm missing something. 
 Otherwise I'm ok to adding that as an option, but only if exporting to a fixed folder remains, since my setup (and I guess not just mine) has the playlists all in one folder. More over importing playlists at batch should then become a process that checks all folders in the music library recursively (since the exporter could arrange them in the appropriate subfolders).

About making paths relative:
It's possible to parse every exported playlist and change the paths of the items to be relative to a directory (that should be chosen in the settings). That should be a simple loop for all the lines in the m3u (disregarding #...) where the path is replaced with a relative one. Here's a discussion on making paths relative in python: https://stackoverflow.com/questions/7287996/python-get-relative-path-from-comparing-two-absolute-paths

**Comment by v-ko** [comment]
Done in https://github.com/petko10/rhythmbox-plugin-playlists-import-export/commit/006b93628546ab24a883ae7960ca8440b3d424b4
